//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurfaceApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurfaceApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMUTE [Device hybridDevice_1(absDevice,absDevice2), Device hybridDevice_2(absDevice2,absDevice)].
        /// </summary>
        public static string permute2 {
            get {
                return ResourceManager.GetString("permute2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMUTE [Device hybridDevice_1(absDevice,absDevice2,absDevice3), Device hybridDevice_2(absDevice,absDevice3,absDevice2), Device hybridDevice_3(absDevice2,absDevice,absDevice3), Device hybridDevice_4(absDevice2,absDevice3,absDevice), Device hybridDevice_5(absDevice3,absDevice,absDevice2), De
        ///vice hybridDevice_6(absDevice3,absDevice2,absDevice)].
        /// </summary>
        public static string permute3 {
            get {
                return ResourceManager.GetString("permute3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMUTE [Device hybridDevice_1(absDevice,absDevice2,absDevice3,absDevice4), Device hybridDevice_2(absDevice,absDevice2,absDevice4,absDevice3), Device hybridDevice_3(absDevice,absDevice3,absDevice2,absDevice4), Device hybridDevice_4(absDevice,absDevice3,absDevice4,absDevice2), Device hybridD
        ///evice_5(absDevice,absDevice4,absDevice2,absDevice3), Device hybridDevice_6(absDevice,absDevice4,absDevice3,absDevice2), Device hybridDevice_7(absDevice2,absDevice,absDevice3,absDevice4), Device hybridDevice_8(absDevice2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string permute4 {
            get {
                return ResourceManager.GetString("permute4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMUTE [Device hybridDevice_1(absDevice,absDevice2,absDevice3,absDevice4,absDevice5), Device hybridDevice_2(absDevice,absDevice2,absDevice3,absDevice5,absDevice4), Device hybridDevice_3(absDevice,absDevice2,absDevice4,absDevice3,absDevice5), Device hybridDevice_4(absDevice,absDevice2,absDe
        ///vice4,absDevice5,absDevice3), Device hybridDevice_5(absDevice,absDevice2,absDevice5,absDevice3,absDevice4), Device hybridDevice_6(absDevice,absDevice2,absDevice5,absDevice4,absDevice3), Device hybridDevice_7(absDevice,a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string permute5 {
            get {
                return ResourceManager.GetString("permute5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMUTE [Device hybridDevice_1(absDevice,absDevice2,absDevice3,absDevice4,absDevice5,absDevice6), Device hybridDevice_2(absDevice,absDevice2,absDevice3,absDevice4,absDevice6,absDevice5), Device hybridDevice_3(absDevice,absDevice2,absDevice3,absDevice5,absDevice4,absDevice6), Device hybridDe
        ///vice_4(absDevice,absDevice2,absDevice3,absDevice5,absDevice6,absDevice4), Device hybridDevice_5(absDevice,absDevice2,absDevice3,absDevice6,absDevice4,absDevice5), Device hybridDevice_6(absDevice,absDevice2,absDevice3,ab [rest of string was truncated]&quot;;.
        /// </summary>
        public static string permute6 {
            get {
                return ResourceManager.GetString("permute6", resourceCulture);
            }
        }
    }
}
